### PR TITLE
Correct leading space

### PR DESCRIPTION
**Pull request by mikkelbu**
To make the left margins align (see the problem on the image below).
The Designer file has been regenerated to match the resx-file.
image

### CODE REVIEW

**Comment by karmi** [comment]
Hi @mikkelbu, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/windows-installers/pull/8.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by mikkelbu** [comment]
Hi @karmi. The email should be added now. I made a mistake when I created the commit.

**Comment by karmi** [comment]
Hi @mikkelbu, thanks!, all green now!

**Comment by russcam** [comment]
Thanks @mikkelbu 👍

**Pull request merged**
